### ISSUE TITLE
New Release Needed

### ISSUE THREAD

**Issue by dwmunster** [go-joe/file-memory#1]
The latest release (v0.2.0) uses an old Storage interface (returns `string` instead of `[]byte`). Users running `go get github.com/go-joe/file-memory` will not be able to use joe v0.8.0.

**Comment by fgrosse** [comment]
Yes you are right, seems like I did the update but forgot to tag a new release.
This is now fixed via https://github.com/go-joe/file-memory/releases/tag/v0.3.0

Thanks for pointing this out :+1:
